### ISSUE TITLE
how to run this on gtx850m 

### ISSUE THREAD

**Issue by WantYKnow** [macaodha/inat_comp_2018#1]
My video card memory is 2g, how to modify this code to run on my own computer.

**Comment by macaodha** [comment]
You will have to check what version of cuda your device will support and perhaps compile PyTorch from scratch if the built versions do not support it. 
https://discuss.pytorch.org/t/cuda-runtime-error-8-invalid-device-function/3584

If you dont want to train the model, and only run it during test, you should be able to only use the CPU.
