### ISSUE TITLE
how can I get the model's PR or ROC data?

### ISSUE THREAD

**Issue by wantlknow** [macaodha/inat_comp_2018#2]
I am very sorry to disturb you again.Firstly, thanks for your help in the last question.
As the title says，how can I get them without retrain this model again. Or how can view this file "iNat_2018_InceptionV3.pth.tar".

**Comment by macaodha** [comment]
The pre-trained model is available [here](http://vision.caltech.edu/~macaodha/inat2018/iNat_2018_InceptionV3.pth.tar)
